services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      - MYSQL_DATABASE=inventory
      - MYSQL_PASSWORD=sagarmatha
      - MYSQL_ROOT_PASSWORD=sagarmatha
      - MYSQL_USER=sandesh
    ports:
      - 3306:3306
    expose:
      - 3306
